@startuml
title "Теплый дом" Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы")
System(WarmHouse, "Теплый дом", "Система подключения и управления устройствами")

System_Ext(connectingDevices, "Подключение устройств", "Подключение устройств и программирования модулей")
System_Ext(deviceManagement, "Управление устройствами", "Взаимодействие с устройствами")

Rel(user, WarmHouse, "Взаимодействие с системой")
Rel(WarmHouse,connectingDevices, "Подключения устройств")
Rel(WarmHouse,deviceManagement, "Управление разными устройствами")

@enduml